- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/29)
> just to check reviewable

- .gitignore
- package/cloudshell/cp/aws/models/deploy_aws_ec2_ami_instance_resource_model.py
adding more attributes to the deploy_aws_ec2_ami_instance_resource_model
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/42)
> setting deploy attributes

- drivers/aws_shell_driverPackage/DataModel/datamodel.xml
adding generic input to datamodel.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/57)
> adding Generic Input to datamodel.xml

- package/cloudshell/cp/aws/domain/services/ec2_services/aws_security_group_service.py
- package/tests/test_security_groups/test_security_groups.py
Testing security groups
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/66)
> Testing security groups

- drivers/aws_shell_driver/src/driver.py
- drivers/aws_shell_driver/src/requirements.txt
- drivers/aws_shell_driverPackage/DataModel/datamodel.xml
- drivers/deployment_drivers/aws_ec2_ami_instance/driver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/68)
> small cleanups

- package/cloudshell/__init__.py
- package/cloudshell/cp/__init__.py
- package/cloudshell/cp/aws/__init__.py
- package/cloudshell/cp/aws/common/__init__.py
- package/cloudshell/cp/aws/device_access_layer/__init__.py
- package/cloudshell/cp/aws/device_access_layer/models/__init__.py
- package/cloudshell/cp/aws/domain/__init__.py
- package/cloudshell/cp/aws/domain/ami_management/__init__.py
- package/cloudshell/cp/aws/domain/ami_management/operations/__init__.py
- package/cloudshell/cp/aws/domain/common/__init__.py
- package/cloudshell/cp/aws/domain/networking/__init__.py
- package/cloudshell/cp/aws/domain/networking/models/__init__.py
- package/cloudshell/cp/aws/domain/networking/operations/__init__.py
- package/cloudshell/cp/aws/domain/services/__init__.py
- package/cloudshell/cp/aws/domain/services/ec2_services/__init__.py
- package/cloudshell/cp/aws/domain/services/model_parser/__init__.py
- package/cloudshell/cp/aws/domain/services/session_providers/__init__.py
- package/cloudshell/cp/aws/domain/services/storage_services/__init__.py
- package/cloudshell/cp/aws/domain/services/task_manager/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/82)
> updating init files to try and solve vooodooo

- package/tests/test_ami_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/85)
> adding unittest to deploy operation

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/87)
> Update README.md with coverage badge

- drivers/aws_shell/src/driver.py
added command PrepareConnectivity on CP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/96)
> added command PrepareConnectivity on CP

- drivers/aws_shell/src/driver.py
- drivers/aws_shell/src/drivermetadata.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/97)
> fixed aws_shell driver interface

- drivers/aws_shell/src/driver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/120)
> Fixed CleanupConnectivity interface

- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/126)
> fixed run time error

- drivers/aws_shell/src/driver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/155)
> added autoload

- drivers/aws_shell/src/driver.py
- drivers/aws_shell/src/drivermetadata.xml
#149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/166)
> removed "Apply Connectivity Changes" from aws driver

- package/cloudshell/cp/aws/aws_shell.py
- package/tests/test_ami_management/test_operations/test_refresh_ip_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/168)
> added test on refresh_ip_operation

- package/cloudshell/cp/aws/aws_shell.py
- package/cloudshell/cp/aws/domain/ami_management/operations/delete_operation.py
- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/domain/services/ec2/security_group.py
- package/cloudshell/cp/aws/domain/services/ec2/tags.py
- package/tests/test_ami_management/test_operations/test_delete_operation.py
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
- package/tests/test_domain_services/test_security_groups.py
- package/tests/test_domain_services/test_subnet.py
- package/tests/test_domain_services/test_tag_service.py
1. Fixed delete of exclusive security group during delete operation
2. Removing allow all outbound ports rule from exclusive security group
3. Fixed failing tests
#83 + #154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/169)
> Fixing #83 + #154 

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/domain/services/ec2/instance_credentials.py
- package/tests/test_domain_services/test_ami_creds_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/174)
> user root added as default for unix

- package/cloudshell/cp/aws/aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/176)
> fix package

- package/cloudshell/cp/aws/domain/conncetivity/operations/cleanup.py
- package/cloudshell/cp/aws/domain/services/ec2/keypair.py
- package/tests/test_connectivity/test_cleanup_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/178)
> added  : remove_key_pair_for_reservation_in_ec2

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/185)
> fixing documentation

- drivers/aws_shell/src/driver.py
- package/cloudshell/cp/aws/aws_shell.py
- package/tests/test_aws_shell.py
fixed delete from inventory issue
and also renamed delete_ami to delete_instance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/187)
> fixed delete from inventory issue

- package/cloudshell/cp/aws/domain/services/ec2/instance.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/192)
> Changed the deploy_ami to use the default bot waiter instead of our custom waiter

- package/cloudshell/cp/aws/domain/ami_management/operations/power_operation.py
- package/tests/test_ami_management/test_operations/test_power_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/209)
> fixed concurrency problems

- drivers/aws_shell/src/requirements.txt
- drivers/deployment_drivers/aws_ec2_ami_instance/requirements.txt
- package/cloudshell/cp/aws/aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/212)
> fixed driver dependencies

- package/cloudshell/cp/aws/aws_shell.py
- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/cleanup.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/cloudshell/cp/aws/domain/services/ec2/instance.py
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
- package/tests/test_connectivity/test_cleanup_connectivity.py
- package/tests/test_connectivity/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/213)
> added some logging

- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/cloudshell/cp/aws/domain/services/ec2/route_table.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/215)
> try to fix prepare connectivity problems

- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/216)
> fixing route creation bug

- drivers/aws_shell/src/requirements.txt
- drivers/deployment_drivers/aws_ec2_ami_instance/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/228)
> add change to requirements

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/231)
> change description inbound and out bound

- cloudformation/0_Main.json
- cloudformation/0_Main_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/239)
> Updated with N.California public AMI ES

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/domain/services/ec2/instance.py
- package/tests/test_domain_services/test_instance_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/252)
> Added logs when instance_status_ok

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/259)
> Fixed Instace Type and Storage Type attributes description

- drivers/aws_shellPackage/Configuration/shellconfig.xml
- drivers/aws_shellPackage/DataModel/datamodel.xml
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/264)
> renamed attributes

- cloudformation/0_Main.json
- cloudformation/0_Main_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/265)
> Removed comma from the main Json files

- package/cloudshell/cp/aws/domain/services/ec2/vpc.py
- package/cloudshell/cp/aws/domain/services/waiters/vpc_peering.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/266)
> refactored vpc peering createion to increase stability

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/273)
> fixed Networks In Use description that it supportes any CIDR

- package/cloudshell/cp/aws/aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/277)
> added with ErrorHandlingContext(shell_context.logger):

- package/cloudshell/cp/aws/aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/279)
> added with ErrorHandlingContext to aws_shell to fix error handling

- cloudformation/0_Main.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/282)
> Fixing cf ami refs

- cloudformation/0_Main_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/283)
> fix ex cf json

- cloudformation/0_Main.json
- cloudformation/0_Main_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/285)
> fixed availability zone for sao paolo

- drivers/aws_shellPackage/DataModel/datamodel.xml
- drivers/deployment_drivers/aws_ec2_ami_instance/driver.py
Use "cloudProviderName" from context instead of "Cloud Provider" attribute in App driver
NO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/294)
> Task 30 Refactor retriving of attribute "Cloud Provider"

- cloudformation/0_Main.json
- cloudformation/0_Main_EX.json
- cloudformation/2_EC2.json
- cloudformation/2_EC2_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/315)
> task 314 QualiX 2.4 - update AWS CF AMI to install latest QX

- cloudformation/0_Main.json
- cloudformation/0_Main_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/318)
> Added us-east-2 (Ohio) to CF

- cloudformation/0_Main.json
- cloudformation/0_Main_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/319)
> added availability zones for Ohio region

- cloudformation/1_VPC.json
- cloudformation/1_VPC_EX.json
- Added unit tests to validate all CF jsons are valid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/323)
> Added port 443 to QualiX SG

- drivers/aws_shellPackage/DataModel/datamodel.xml
Added the following regions:
- us-east-2 - US East (Ohio)
- us-west-1 - US West (N. California)
- ap-northeast-2 -  Asia Pacific (Seoul)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/326)
> Added more regions to the cloud provider

- cloudformation/2_EC2.json
- cloudformation/2_EC2_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/328)
> update qx userdata

- cloudformation/2_EC2.json
- cloudformation/2_EC2_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/334)
> fixed userdata script for execution server installation

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/335)
> add the AllowRemoteConnection flag to the cloud provider family

- kill_python.bat
- package/cloudshell/cp/aws/domain/services/waiters/instance.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/342)
> fixing instance status ok waiter

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/343)
> added validation on image (ami) load

- drivers/aws_shell/src/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/346)
> fix requirements.txt

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/347)
> Added ExecutionServerSelector to datamodel.xml

- drivers/aws_shellPackage/Configuration/shellconfig.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/348)
> Added ExecutionServerSelector to resource template

- package/cloudshell/cp/aws/domain/ami_management/operations/refresh_ip_operation.py
- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/360)
> added 2nd gen shell attributes support

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/361)
> Removed searchable flag from CLP family

- drivers/aws_shellPackage/DataModel/datamodel.xml
- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
- package/cloudshell/cp/aws/models/aws_ec2_cloud_provider_resource_model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/364)
> Reserved IPs in Subnet attribute added.

- cloudformation/2_EC2_EX_No_VPN.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/366)
> Gil change to static ip

- cloudformation/2_EC2_EX_No_VPN.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/367)
> removed subnet

- cloudformation/2_EC2_EX_No_VPN.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/368)
> security group

- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
- package/tests/test_domain_services/test_elastic_ip.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/371)
> Fixed deploy tests

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
- package/tests/test_common/test_cancellation_service.py
- package/tests/test_domain_services/test_subnet.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/373)
> removed old code and added unit test

- package/cloudshell/cp/aws/aws_shell.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/cleanup.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/cloudshell/cp/aws/domain/services/ec2/route_table.py
- package/cloudshell/cp/aws/domain/services/ec2/vpc.py
- package/tests/test_domain_services/test_route_table.py
- package/tests/test_domain_services/test_vpc.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/374)
> Added support in Public/Private subnets

- .coveragerc
- kill_python.bat
- package/cloudshell/cp/aws/aws_shell.py
- package/cloudshell/cp/aws/common/retry_helper.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare_subnet_executor.py
- package/cloudshell/cp/aws/domain/services/ec2/route_table.py
- package/cloudshell/cp/aws/domain/services/ec2/subnet.py
- package/cloudshell/cp/aws/domain/services/ec2/tags.py
- package/cloudshell/cp/aws/domain/services/ec2/vpc.py
- package/cloudshell/cp/aws/domain/services/parsers/connection_params.py
- package/cloudshell/cp/aws/domain/services/waiters/subnet.py
- package/cloudshell/cp/aws/models/network_actions_models.py
- package/tests/test_connectivity/test_prepare_connectivity.py
- package/tests/test_connectivity/test_prepare_subnet_executor.py
- package/tests/test_domain_services/test_route_table.py
- package/tests/test_domain_services/test_subnet.py
- package/tests/test_domain_services/test_vpc.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/376)
> Semi parallel prepare subnets & tests

- drivers/aws_shell/src/driver.py
- drivers/aws_shell/src/drivermetadata.xml
- install_to_drop.bat
- package/cloudshell/cp/aws/aws_shell.py
- package/cloudshell/cp/aws/common/deploy_data_holder.py
- package/cloudshell/cp/aws/domain/common/exceptions.py
- package/cloudshell/cp/aws/domain/deployed_app/operations/set_app_security_groups.py
- package/cloudshell/cp/aws/domain/services/ec2/security_group.py
- package/cloudshell/cp/aws/domain/services/ec2/tags.py
- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
- package/cloudshell/cp/aws/domain/services/parsers/port_group_attribute_parser.py
- package/cloudshell/cp/aws/domain/services/parsers/security_group_parser.py
- package/cloudshell/cp/aws/models/app_security_groups_model.py
- package/cloudshell/cp/aws/models/network_actions_models.py
- package/tests/test_deployed_app/test_operations/test_set_app_security_groups_operation.py
- package/tests/test_domain_services/test_security_groups.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/382)
> Igor 163030 add custom security groups

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/383)
> added isolate app attribute

- package/cloudshell/cp/aws/aws_shell.py
- package/cloudshell/cp/aws/domain/deployed_app/operations/app_ports_operation.py
- package/cloudshell/cp/aws/domain/services/ec2/security_group.py
- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
- package/tests/test_aws_shell.py
- package/tests/test_deployed_app/test_operations/test_app_ports_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/385)
> Igor 163306 get app ports

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/cloudshell/cp/aws/domain/services/ec2/security_group.py
- package/cloudshell/cp/aws/domain/services/ec2/tags.py
- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
- package/cloudshell/cp/aws/models/deploy_aws_ec2_ami_instance_resource_model.py
- package/tests/test_connectivity/test_prepare_connectivity.py
- package/tests/test_domain_services/test_security_groups.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/386)
> isolate app

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/models/deploy_result_model.py
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
- package/tests/test_aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/389)
> fixed json a bit so network data is part of vm_details

- package/tests/test_aws_shell.py
- package/tests/test_deployed_app/test_operations/test_app_ports_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/391)
> test_get_app_ports_from_cloud_provider added.

- package/cloudshell/cp/aws/domain/common/vm_details_provider.py
- package/tests/test_common/test_vm_details_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/398)
> fixed handling of elastic ip and public ip

- package/cloudshell/cp/aws/domain/common/vm_details_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/399)
> fixed elastic ip only appearing when true

- package/cloudshell/cp/aws/domain/common/vm_details_provider.py
- package/tests/test_common/test_vm_details_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/401)
> always show elastic ip and public ip

- package/cloudshell/cp/aws/domain/common/vm_details_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/402)
> always show platform even if empty

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/403)
> fixed description

- package/cloudshell/cp/aws/domain/common/vm_details_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/404)
> platform will show linux if empty

- cloudformation/0_Main_EX_No_VPN.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/406)
> fixed amiids for windows machine in cloudformation

- package/cloudshell/cp/aws/domain/conncetivity/operations/cleanup.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare_subnet_executor.py
- package/cloudshell/cp/aws/domain/services/ec2/vpc.py
- package/tests/test_connectivity/test_prepare_connectivity.py
- package/tests/test_connectivity/test_prepare_subnet_executor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/407)
> Noam 163434 vpc error msg

- package/cloudshell/cp/aws/domain/services/ec2/instance.py
- package/tests/test_domain_services/test_instance_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/411)
> adding tags to volumes

- package/cloudshell/cp/aws/common/retry_helper.py
- package/cloudshell/cp/aws/domain/services/ec2/elastic_ip.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/414)
> added retry on elastic ip actions

- package/cloudshell/cp/aws/domain/common/list_helper.py
- package/cloudshell/cp/aws/domain/services/ec2/vpc.py
- package/tests/test_domain_services/test_vpc.py
fixed tests.
added test for security group deletion order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/416)
> Noam 164644 vpc not erased

- cloudformation/0_Main_EX.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/417)
> fixing bug in 0_Main_EX.json

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/models/deploy_result_model.py
- package/tests/test_aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/422)
> added vpc id to custom params

- cloudformation/2_EC2.json
- cloudformation/2_EC2_EX.json
- cloudformation/2_EC2_EX_No_VPN.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/426)
> adding the nameservers to the end of the file

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/models/deploy_result_model.py
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
- package/tests/test_aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/427)
> added availability zone to deploy result

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/models/deploy_result_model.py
- package/tests/test_aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/428)
> removed vpc id from deploy result

- drivers/aws_shell/src/driver.py
- drivers/aws_shell/src/drivermetadata.xml
- package/cloudshell/cp/aws/aws_shell.py
- package/tests/test_common/test_get_vm_details.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/429)
> refactor vm details bulk

- package/cloudshell/cp/aws/aws_shell.py
- package/tests/test_common/test_get_vm_details.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/430)
> add app name to vm details

- package/cloudshell/cp/aws/domain/common/vm_details_provider.py
- package/tests/test_common/test_get_vm_details.py
- package/tests/test_common/test_vm_details_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/431)
> added a couple of attributes to awshell

- package/cloudshell/cp/aws/aws_shell.py
- package/cloudshell/cp/aws/domain/context/client_error.py
- package/cloudshell/cp/aws/domain/services/ec2/tags.py
- package/tests/test_domain_services/test_tag_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/434)
> fixing bug 165515

- package/cloudshell/cp/aws/domain/common/vm_details_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/437)
> add device index

- .travis.yml
- drivers/aws_shell/src/requirements.txt
- package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/438)
> update cloudshell-automation-api version

- cloudformation/0_Main.json
- cloudformation/0_Main_EX.json
- cloudformation/0_Main_EX_No_VPN.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/440)
> if not HA mode than we dont try to get 2nd AZ

- external_requirements.txt
- package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/442)
> add python-dateutil==2.6.1 to beggining of requirements file

- external_requirements.txt
- package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/446)
> removed python-dateutil requirement

- package/cloudshell/cp/aws/aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/447)
> removed calls  to SetResourceLiveStatus when power commands

- drivers/aws_shellPackage/DataModel/datamodel.xml
- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/domain/common/vm_details_provider.py
- package/cloudshell/cp/aws/domain/services/ec2/instance.py
- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
- package/cloudshell/cp/aws/models/ami_deployment_model.py
- package/cloudshell/cp/aws/models/deploy_aws_ec2_ami_instance_resource_model.py
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
- package/tests/test_common/test_vm_details_provider.py
- package/tests/test_domain_services/test_instance_service.py
- package/tests/test_domain_services/test_model_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/451)
> support for iam role

- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/453)
> remove spurious stuff

- package/cloudshell/cp/aws/common/retry_helper.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/cloudshell/cp/aws/domain/services/ec2/elastic_ip.py
- package/cloudshell/cp/aws/domain/services/ec2/vpc.py
- package/cloudshell/cp/aws/domain/services/waiters/instance.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/458)
> Increasing retry max attempts

- .travis.yml
- package/cloudshell/cp/aws/aws_shell.py
- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare_subnet_executor.py
- package/cloudshell/cp/aws/domain/deployed_app/operations/set_app_security_groups.py
- package/cloudshell/cp/aws/domain/services/ec2/elastic_ip.py
- package/cloudshell/cp/aws/domain/services/parsers/connection_params.py
- package/cloudshell/cp/aws/domain/services/parsers/network_actions.py
- package/cloudshell/cp/aws/domain/services/strategy/device_index.py
- package/cloudshell/cp/aws/models/deploy_result_model.py
- package/cloudshell/cp/aws/models/network_actions_models.py
- package/requirements.txt
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
- package/tests/test_aws_shell.py
- package/tests/test_connectivity/test_prepare_connectivity.py
- package/tests/test_connectivity/test_prepare_subnet_executor.py
- package/tests/test_domain_services/test_device_index_strategy.py
- package/tests/test_domain_services/test_elastic_ip.py
- package/tests/test_domain_services/test_model_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/460)
> Product Backlog Item 166375: PrepareConnectivity interface changes

- drivers/aws_shell/src/driver.py
- package/cloudshell/cp/aws/domain/services/strategy/device_index.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/464)
> fix_vnicName

- package/cloudshell/cp/aws/aws_shell.py
- package/cloudshell/cp/aws/domain/common/vm_details_provider.py
- package/tests/test_common/test_get_vm_details.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/465)
> fix vnicName

- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/tests/test_connectivity/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/466)
> fix s3 not exist

- package/cloudshell/cp/aws/domain/services/ec2/elastic_ip.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/467)
> fix is_single_subnet_mode

- package/cloudshell/cp/aws/aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/468)
> fix import

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/470)
> Fix Attributes

- drivers/aws_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/471)
> removed auto power off attribute from datamodel

- Quali-Shells-Open-Source.rtf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/477)
> adding license open source license

- drivers/aws_shellPackage/Configuration/shellconfig.xml
- drivers/aws_shellPackage/DataModel/datamodel.xml
- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
- package/cloudshell/cp/aws/models/aws_ec2_cloud_provider_resource_model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/479)
> added attributes

- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare.py
- package/cloudshell/cp/aws/domain/conncetivity/operations/prepare_subnet_executor.py
- package/cloudshell/cp/aws/domain/services/ec2/security_group.py
- package/cloudshell/cp/aws/models/aws_ec2_cloud_provider_resource_model.py
- package/tests/test_connectivity/test_prepare_connectivity.py
- package/tests/test_domain_services/test_security_groups.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/484)
> Static networks/prepare connectivity

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/485)
> fixing cidr allocation in multiple static subnetss

- drivers/aws_shellPackage/DataModel/datamodel.xml
- package/cloudshell/cp/aws/domain/services/parsers/aws_model_parser.py
- package/cloudshell/cp/aws/models/aws_ec2_cloud_provider_resource_model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/486)
> added descriptions, removed an attribute

- drivers/aws_shellPackage/DataModel/datamodel.xml
- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/cloudshell/cp/aws/domain/services/ec2/instance.py
- package/cloudshell/cp/aws/models/ami_deployment_model.py
- package/cloudshell/cp/aws/models/deploy_aws_ec2_ami_instance_resource_model.py
- package/tests/test_domain_services/test_instance_service.py
- package/tests/test_domain_services/test_model_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/487)
> added user data parameters

- package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/489)
> fixed ipaddress version

- drivers/aws_shell/src/driver.py
- package/cloudshell/cp/aws/aws_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/493)
> added AddCustomTags hidden connected command

- cloudformation/AMI_Lookup.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/497)
> zipfile cannot be used with nodejs10.x, only nodejs8.10

- package/cloudshell/cp/aws/domain/ami_management/operations/deploy_operation.py
- package/tests/test_ami_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/499)
> support 2nd gen deployed app resources

- cloudformation/AMI_Lookup.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/502)
> comma syntax

- package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/511)
> changed boto3 requirement

- package/cloudshell/cp/aws/domain/conncetivity/operations/traffic_mirroring_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/513)
> fix bad validation of schema during create

- package/cloudshell/cp/aws/domain/conncetivity/operations/traffic_mirroring_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/aws-shell/514)
> session number not mandatory
